{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.module_test",
    "module": "flutter_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_debug",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-1.0.aar",
          "url": "flutter_debug-1.0.aar",
          "size": 15543658,
          "sha512": "06a8ef2e99420c3507f3994c55f4502f5a1e39c986eaff26e8c19efc96c82c40399a1655aef7fc44b07aa0f3494580b91323dee5f12aa13060da5446fcbedb37",
          "sha256": "ce4b3baa7f3fd691fa7d53b69689658007fc984a98605c4e0ca2ba16a7704684",
          "sha1": "59c6d2babafebafd7b94d9d30f95631b9e9cb1a2",
          "md5": "7ac5720c248643c24eac06c2bb91a584"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_debug",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-1.0.aar",
          "url": "flutter_debug-1.0.aar",
          "size": 15543658,
          "sha512": "06a8ef2e99420c3507f3994c55f4502f5a1e39c986eaff26e8c19efc96c82c40399a1655aef7fc44b07aa0f3494580b91323dee5f12aa13060da5446fcbedb37",
          "sha256": "ce4b3baa7f3fd691fa7d53b69689658007fc984a98605c4e0ca2ba16a7704684",
          "sha1": "59c6d2babafebafd7b94d9d30f95631b9e9cb1a2",
          "md5": "7ac5720c248643c24eac06c2bb91a584"
        }
      ]
    }
  ]
}
